// <auto-generated />
using System;
using Character.Service.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Character.Service.Migrations
{
    [DbContext(typeof(CharacterDbContext))]
    [Migration("20260804053200_AddRoomStateSaves")]
    partial class AddRoomStateSaves
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("character")
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Character.Service.Models.CharacterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Archetype")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EquipmentJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("InventoryJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("QuestsJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("OwnerId", "Name")
                        .IsUnique();

                    b.ToTable("characters", "character");
                });

            modelBuilder.Entity("Character.Service.Models.CharacterSaveEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AllocatedPointsJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentExp")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentLevel")
                        .HasColumnType("integer");

                    b.Property<string>("CurrentScene")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("DeathCount")
                        .HasColumnType("integer");

                    b.Property<string>("EquipmentJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("InventoryJson")
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsAlive")
                        .HasColumnType("boolean");

                    b.Property<short>("PlayerRole")
                        .HasColumnType("smallint");

                    b.Property<int>("PlaytimeSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("RoomCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId", "CapturedAt")
                        .IsDescending(false, true);

                    b.ToTable("character_saves", "character");
                });

            modelBuilder.Entity("Character.Service.Models.CharacterSessionEntity", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("AllocatedPointsJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentExp")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentLevel")
                        .HasColumnType("integer");

                    b.Property<int>("DeathCount")
                        .HasColumnType("integer");

                    b.Property<string>("EquipmentJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("InventoryJson")
                        .HasColumnType("jsonb");

                    b.Property<short>("PlayerRole")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CharacterId", "SessionId");

                    b.HasIndex("SessionId");

                    b.ToTable("character_session", "character");
                });

            modelBuilder.Entity("Character.Service.Models.RoomStateSaveEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentScene")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("FogJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("PlayTimeSeconds")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("WorldStatesJson")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "CapturedAt")
                        .IsDescending(false, true);

                    b.ToTable("room_state_saves", "character");
                });

            modelBuilder.Entity("Character.Service.Models.SessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentScene")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FogJson")
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsMultiplayer")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastPlayedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("PlayTimeSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("RoomCode")
                        .IsUnique();

                    b.ToTable("sessions", "character");
                });

            modelBuilder.Entity("Character.Service.Models.WorldStateEntity", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Progress")
                        .HasColumnType("integer");

                    b.Property<short>("StateValue")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SessionId", "EventId");

                    b.ToTable("world_state", "character");
                });

            modelBuilder.Entity("Character.Service.Models.CharacterEntity", b =>
                {
                    b.OwnsMany("Character.Service.Models.CharacterSnapshot", "Snapshots", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<DateTime>("CapturedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("CharacterId")
                                .HasColumnType("uuid");

                            b1.Property<string>("EventType")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<int>("Gold")
                                .HasColumnType("integer");

                            b1.Property<int>("Hp")
                                .HasColumnType("integer");

                            b1.Property<bool>("IsAlive")
                                .HasColumnType("boolean");

                            b1.Property<int>("Level")
                                .HasColumnType("integer");

                            b1.Property<int>("MaxHp")
                                .HasColumnType("integer");

                            b1.Property<int>("PlaytimeSeconds")
                                .HasColumnType("integer");

                            b1.Property<string>("RoomCode")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");

                            b1.HasKey("Id");

                            b1.HasIndex("CharacterId", "CapturedAt");

                            b1.ToTable("character_snapshots", "character");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("Character.Service.Models.CharacterSaveEntity", b =>
                {
                    b.OwnsOne("Character.Service.Models.CombatStats", "Combat", b1 =>
                        {
                            b1.Property<long>("CharacterSaveEntityId")
                                .HasColumnType("bigint");

                            b1.Property<int>("Ad")
                                .HasColumnType("integer")
                                .HasColumnName("Ad");

                            b1.Property<int>("Ap")
                                .HasColumnType("integer")
                                .HasColumnName("Ap");

                            b1.Property<float>("AttackSpeed")
                                .HasColumnType("real")
                                .HasColumnName("AttackSpeed");

                            b1.Property<int>("Def")
                                .HasColumnType("integer")
                                .HasColumnName("Def");

                            b1.Property<int>("HealthCharges")
                                .HasColumnType("integer")
                                .HasColumnName("HealthCharges");

                            b1.Property<int>("ManaCharges")
                                .HasColumnType("integer")
                                .HasColumnName("ManaCharges");

                            b1.Property<int>("PotionMaxFlasks")
                                .HasColumnType("integer")
                                .HasColumnName("PotionMaxFlasks");

                            b1.Property<int>("PotionMaxManaFlasks")
                                .HasColumnType("integer")
                                .HasColumnName("PotionMaxManaFlasks");

                            b1.Property<int>("Res")
                                .HasColumnType("integer")
                                .HasColumnName("Res");

                            b1.HasKey("CharacterSaveEntityId");

                            b1.ToTable("character_saves", "character");

                            b1.WithOwner()
                                .HasForeignKey("CharacterSaveEntityId");
                        });

                    b.OwnsOne("Character.Service.Models.Position", "Position", b1 =>
                        {
                            b1.Property<long>("CharacterSaveEntityId")
                                .HasColumnType("bigint");

                            b1.Property<string>("LastRestPointId")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("LastRestPointId");

                            b1.Property<float>("PosX")
                                .HasColumnType("real")
                                .HasColumnName("PosX");

                            b1.Property<float>("PosY")
                                .HasColumnType("real")
                                .HasColumnName("PosY");

                            b1.Property<float>("PosZ")
                                .HasColumnType("real")
                                .HasColumnName("PosZ");

                            b1.HasKey("CharacterSaveEntityId");

                            b1.ToTable("character_saves", "character");

                            b1.WithOwner()
                                .HasForeignKey("CharacterSaveEntityId");
                        });

                    b.OwnsOne("Character.Service.Models.VitalStats", "Vitals", b1 =>
                        {
                            b1.Property<long>("CharacterSaveEntityId")
                                .HasColumnType("bigint");

                            b1.Property<int>("CurrentHp")
                                .HasColumnType("integer")
                                .HasColumnName("CurrentHp");

                            b1.Property<int>("CurrentMana")
                                .HasColumnType("integer")
                                .HasColumnName("CurrentMana");

                            b1.Property<int>("MaxHp")
                                .HasColumnType("integer")
                                .HasColumnName("MaxHp");

                            b1.Property<int>("MaxMana")
                                .HasColumnType("integer")
                                .HasColumnName("MaxMana");

                            b1.Property<int>("MaxStamina")
                                .HasColumnType("integer")
                                .HasColumnName("MaxStamina");

                            b1.HasKey("CharacterSaveEntityId");

                            b1.ToTable("character_saves", "character");

                            b1.WithOwner()
                                .HasForeignKey("CharacterSaveEntityId");
                        });

                    b.Navigation("Combat")
                        .IsRequired();

                    b.Navigation("Position")
                        .IsRequired();

                    b.Navigation("Vitals")
                        .IsRequired();
                });

            modelBuilder.Entity("Character.Service.Models.CharacterSessionEntity", b =>
                {
                    b.HasOne("Character.Service.Models.SessionEntity", "Session")
                        .WithMany("Characters")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Character.Service.Models.CombatStats", "Combat", b1 =>
                        {
                            b1.Property<Guid>("CharacterSessionEntityCharacterId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("CharacterSessionEntitySessionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Ad")
                                .HasColumnType("integer")
                                .HasColumnName("Ad");

                            b1.Property<int>("Ap")
                                .HasColumnType("integer")
                                .HasColumnName("Ap");

                            b1.Property<float>("AttackSpeed")
                                .HasColumnType("real")
                                .HasColumnName("AttackSpeed");

                            b1.Property<int>("Def")
                                .HasColumnType("integer")
                                .HasColumnName("Def");

                            b1.Property<int>("HealthCharges")
                                .HasColumnType("integer")
                                .HasColumnName("HealthCharges");

                            b1.Property<int>("ManaCharges")
                                .HasColumnType("integer")
                                .HasColumnName("ManaCharges");

                            b1.Property<int>("PotionMaxFlasks")
                                .HasColumnType("integer")
                                .HasColumnName("PotionMaxFlasks");

                            b1.Property<int>("PotionMaxManaFlasks")
                                .HasColumnType("integer")
                                .HasColumnName("PotionMaxManaFlasks");

                            b1.Property<int>("Res")
                                .HasColumnType("integer")
                                .HasColumnName("Res");

                            b1.HasKey("CharacterSessionEntityCharacterId", "CharacterSessionEntitySessionId");

                            b1.ToTable("character_session", "character");

                            b1.WithOwner()
                                .HasForeignKey("CharacterSessionEntityCharacterId", "CharacterSessionEntitySessionId");
                        });

                    b.OwnsOne("Character.Service.Models.Position", "Position", b1 =>
                        {
                            b1.Property<Guid>("CharacterSessionEntityCharacterId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("CharacterSessionEntitySessionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("LastRestPointId")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("LastRestPointId");

                            b1.Property<float>("PosX")
                                .HasColumnType("real")
                                .HasColumnName("PosX");

                            b1.Property<float>("PosY")
                                .HasColumnType("real")
                                .HasColumnName("PosY");

                            b1.Property<float>("PosZ")
                                .HasColumnType("real")
                                .HasColumnName("PosZ");

                            b1.HasKey("CharacterSessionEntityCharacterId", "CharacterSessionEntitySessionId");

                            b1.ToTable("character_session", "character");

                            b1.WithOwner()
                                .HasForeignKey("CharacterSessionEntityCharacterId", "CharacterSessionEntitySessionId");
                        });

                    b.OwnsOne("Character.Service.Models.VitalStats", "Vitals", b1 =>
                        {
                            b1.Property<Guid>("CharacterSessionEntityCharacterId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("CharacterSessionEntitySessionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("CurrentHp")
                                .HasColumnType("integer")
                                .HasColumnName("CurrentHp");

                            b1.Property<int>("CurrentMana")
                                .HasColumnType("integer")
                                .HasColumnName("CurrentMana");

                            b1.Property<int>("MaxHp")
                                .HasColumnType("integer")
                                .HasColumnName("MaxHp");

                            b1.Property<int>("MaxMana")
                                .HasColumnType("integer")
                                .HasColumnName("MaxMana");

                            b1.Property<int>("MaxStamina")
                                .HasColumnType("integer")
                                .HasColumnName("MaxStamina");

                            b1.HasKey("CharacterSessionEntityCharacterId", "CharacterSessionEntitySessionId");

                            b1.ToTable("character_session", "character");

                            b1.WithOwner()
                                .HasForeignKey("CharacterSessionEntityCharacterId", "CharacterSessionEntitySessionId");
                        });

                    b.Navigation("Combat")
                        .IsRequired();

                    b.Navigation("Position")
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("Vitals")
                        .IsRequired();
                });

            modelBuilder.Entity("Character.Service.Models.RoomStateSaveEntity", b =>
                {
                    b.HasOne("Character.Service.Models.SessionEntity", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Character.Service.Models.WorldStateEntity", b =>
                {
                    b.HasOne("Character.Service.Models.SessionEntity", "Session")
                        .WithMany("WorldStates")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Character.Service.Models.SessionEntity", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("WorldStates");
                });
#pragma warning restore 612, 618
        }
    }
}
