// <auto-generated />
using System;
using Character.Service.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Character.Service.Migrations
{
    [DbContext(typeof(CharacterDbContext))]
    [Migration("20260714050000_AddPotionMaxManaFlasks")]
    partial class AddPotionMaxManaFlasks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("character")
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Character.Service.Models.CharacterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Archetype")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EquipmentJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("InventoryJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("QuestsJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("OwnerId", "Name")
                        .IsUnique();

                    b.ToTable("characters", "character");
                });

            modelBuilder.Entity("Character.Service.Models.CharacterSessionEntity", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("AllocatedPointsJson")
                        .HasColumnType("jsonb");

                    b.Property<float>("AttackSpeed")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentExp")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentHp")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentLevel")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentMana")
                        .HasColumnType("integer");

                    b.Property<string>("EquipmentJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("InventoryJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("LastRestPointId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("MaxHp")
                        .HasColumnType("integer");

                    b.Property<int>("MaxMana")
                        .HasColumnType("integer");

                    b.Property<int>("MaxStamina")
                        .HasColumnType("integer");

                    b.Property<short>("PlayerRole")
                        .HasColumnType("smallint");

                    b.Property<float>("PosX")
                        .HasColumnType("real");

                    b.Property<float>("PosY")
                        .HasColumnType("real");

                    b.Property<int>("PotionMaxFlasks")
                        .HasColumnType("integer");

                    b.Property<int>("PotionMaxManaFlasks")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CharacterId", "SessionId");

                    b.HasIndex("SessionId");

                    b.ToTable("character_session", "character");
                });

            modelBuilder.Entity("Character.Service.Models.SessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentScene")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsMultiplayer")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastPlayedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("PlayTimeSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("RoomCode")
                        .IsUnique();

                    b.ToTable("sessions", "character");
                });

            modelBuilder.Entity("Character.Service.Models.WorldStateEntity", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Progress")
                        .HasColumnType("integer");

                    b.Property<short>("StateValue")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SessionId", "EventId");

                    b.ToTable("world_state", "character");
                });

            modelBuilder.Entity("Character.Service.Models.CharacterEntity", b =>
                {
                    b.OwnsMany("Character.Service.Models.CharacterSnapshot", "Snapshots", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<DateTime>("CapturedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("CharacterId")
                                .HasColumnType("uuid");

                            b1.Property<string>("EventType")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<int>("Gold")
                                .HasColumnType("integer");

                            b1.Property<int>("Hp")
                                .HasColumnType("integer");

                            b1.Property<bool>("IsAlive")
                                .HasColumnType("boolean");

                            b1.Property<int>("Level")
                                .HasColumnType("integer");

                            b1.Property<int>("MaxHp")
                                .HasColumnType("integer");

                            b1.Property<int>("PlaytimeSeconds")
                                .HasColumnType("integer");

                            b1.Property<string>("RoomCode")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");

                            b1.HasKey("Id");

                            b1.HasIndex("CharacterId", "CapturedAt");

                            b1.ToTable("character_snapshots", "character");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("Character.Service.Models.CharacterSessionEntity", b =>
                {
                    b.HasOne("Character.Service.Models.SessionEntity", "Session")
                        .WithMany("Characters")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Character.Service.Models.WorldStateEntity", b =>
                {
                    b.HasOne("Character.Service.Models.SessionEntity", "Session")
                        .WithMany("WorldStates")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Character.Service.Models.SessionEntity", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("WorldStates");
                });
#pragma warning restore 612, 618
        }
    }
}
