// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Skill.Service.Data;

#nullable disable

namespace Skill.Service.Migrations
{
    [DbContext(typeof(SkillDbContext))]
    [Migration("20260804034414_RenameWoodWindThrustWater")]
    partial class RenameWoodWindThrustWater
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("skill")
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Skill.Service.Models.SkillEntity", b =>
                {
                    b.Property<string>("SkillId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<float>("ActiveEndFrac")
                        .HasColumnType("real");

                    b.Property<float>("ActiveStartFrac")
                        .HasColumnType("real");

                    b.Property<float>("Angle")
                        .HasColumnType("real");

                    b.Property<float>("ApScaling")
                        .HasColumnType("real");

                    b.Property<int>("BaseDamage")
                        .HasColumnType("integer");

                    b.Property<float>("CastTime")
                        .HasColumnType("real");

                    b.Property<float>("Cooldown")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DamageType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Delivery")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Element")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("HitShape")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("IconKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("KnockbackForce")
                        .HasColumnType("real");

                    b.Property<int>("ManaCost")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<float>("OffsetX")
                        .HasColumnType("real");

                    b.Property<float>("OffsetY")
                        .HasColumnType("real");

                    b.Property<int>("ProjectileCount")
                        .HasColumnType("integer");

                    b.Property<float>("ProjectileSpeed")
                        .HasColumnType("real");

                    b.Property<float>("Range")
                        .HasColumnType("real");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<float>("RectHeight")
                        .HasColumnType("real");

                    b.Property<float>("RectWidth")
                        .HasColumnType("real");

                    b.Property<float>("SpreadAngle")
                        .HasColumnType("real");

                    b.Property<float>("SweetSpotMultiplier")
                        .HasColumnType("real");

                    b.Property<float>("SweetSpotRadius")
                        .HasColumnType("real");

                    b.Property<float>("TickInterval")
                        .HasColumnType("real");

                    b.Property<string>("UnityBaselineJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("VfxLifetime")
                        .HasColumnType("real");

                    b.HasKey("SkillId");

                    b.HasIndex("Element");

                    b.ToTable("skills", "skill");
                });
#pragma warning restore 612, 618
        }
    }
}
