--
-- PostgreSQL database dump
--

\restrict aJBUlCgaBEkcGmEadpFiAAdZvaXRj6yBxNBvImVaTK3bUedrLgefQgb2Uj8w4vn

-- Dumped from database version 16.14
-- Dumped by pg_dump version 16.14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: assets; Type: SCHEMA; Schema: -; Owner: attrition_user
--

CREATE SCHEMA assets;


ALTER SCHEMA assets OWNER TO attrition_user;

--
-- Name: character; Type: SCHEMA; Schema: -; Owner: attrition_user
--

CREATE SCHEMA "character";


ALTER SCHEMA "character" OWNER TO attrition_user;

--
-- Name: enemy; Type: SCHEMA; Schema: -; Owner: attrition_user
--

CREATE SCHEMA enemy;


ALTER SCHEMA enemy OWNER TO attrition_user;

--
-- Name: forum; Type: SCHEMA; Schema: -; Owner: attrition_user
--

CREATE SCHEMA forum;


ALTER SCHEMA forum OWNER TO attrition_user;

--
-- Name: identity; Type: SCHEMA; Schema: -; Owner: attrition_user
--

CREATE SCHEMA identity;


ALTER SCHEMA identity OWNER TO attrition_user;

--
-- Name: music; Type: SCHEMA; Schema: -; Owner: attrition_user
--

CREATE SCHEMA music;


ALTER SCHEMA music OWNER TO attrition_user;

--
-- Name: wiki; Type: SCHEMA; Schema: -; Owner: attrition_user
--

CREATE SCHEMA wiki;


ALTER SCHEMA wiki OWNER TO attrition_user;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Assets; Type: TABLE; Schema: assets; Owner: attrition_user
--

CREATE TABLE assets."Assets" (
    "Id" uuid NOT NULL,
    "FileName" text NOT NULL,
    "FilePath" text NOT NULL,
    "AssetType" text NOT NULL,
    "MimeType" text NOT NULL,
    "FileSize" bigint NOT NULL,
    "Title" text,
    "Description" text,
    "Tags" text,
    "UploadedById" uuid,
    "UploadedByName" text,
    "UploadedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone
);


ALTER TABLE assets."Assets" OWNER TO attrition_user;

--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: assets; Owner: attrition_user
--

CREATE TABLE assets."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE assets."__EFMigrationsHistory" OWNER TO attrition_user;

--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: character; Owner: attrition_user
--

CREATE TABLE "character"."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE "character"."__EFMigrationsHistory" OWNER TO attrition_user;

--
-- Name: character_snapshots; Type: TABLE; Schema: character; Owner: attrition_user
--

CREATE TABLE "character".character_snapshots (
    "Id" integer NOT NULL,
    "Level" integer NOT NULL,
    "Hp" integer NOT NULL,
    "MaxHp" integer NOT NULL,
    "Gold" integer NOT NULL,
    "IsAlive" boolean NOT NULL,
    "RoomCode" character varying(32),
    "EventType" character varying(20) NOT NULL,
    "PlaytimeSeconds" integer NOT NULL,
    "CapturedAt" timestamp with time zone NOT NULL,
    "CharacterId" uuid NOT NULL
);


ALTER TABLE "character".character_snapshots OWNER TO attrition_user;

--
-- Name: character_snapshots_Id_seq; Type: SEQUENCE; Schema: character; Owner: attrition_user
--

ALTER TABLE "character".character_snapshots ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "character"."character_snapshots_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: characters; Type: TABLE; Schema: character; Owner: attrition_user
--

CREATE TABLE "character".characters (
    "Id" uuid NOT NULL,
    "OwnerId" uuid NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Archetype" character varying(50) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE "character".characters OWNER TO attrition_user;

--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: enemy; Owner: attrition_user
--

CREATE TABLE enemy."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE enemy."__EFMigrationsHistory" OWNER TO attrition_user;

--
-- Name: enemies; Type: TABLE; Schema: enemy; Owner: attrition_user
--

CREATE TABLE enemy.enemies (
    "EnemyId" character varying(64) NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Tier" character varying(50) NOT NULL,
    "SpawnBiome" text,
    "Hp" integer NOT NULL,
    "Ad" integer NOT NULL,
    "Ap" integer NOT NULL,
    "Def" integer NOT NULL,
    "Res" integer NOT NULL,
    "AttackSpeed" real DEFAULT 1 NOT NULL,
    "IsRanged" boolean NOT NULL,
    "ExpReward" integer NOT NULL,
    "GoldReward" integer NOT NULL,
    "Lore" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE enemy.enemies OWNER TO attrition_user;

--
-- Name: enemy_loot; Type: TABLE; Schema: enemy; Owner: attrition_user
--

CREATE TABLE enemy.enemy_loot (
    "Id" integer NOT NULL,
    "ItemName" character varying(100) NOT NULL,
    "Rarity" character varying(50) NOT NULL,
    "IconKey" text,
    "DropChance" real NOT NULL,
    "MinQty" smallint NOT NULL,
    "MaxQty" smallint NOT NULL,
    "EnemyId" character varying(64) NOT NULL
);


ALTER TABLE enemy.enemy_loot OWNER TO attrition_user;

--
-- Name: enemy_loot_Id_seq; Type: SEQUENCE; Schema: enemy; Owner: attrition_user
--

ALTER TABLE enemy.enemy_loot ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME enemy."enemy_loot_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ForumCategories; Type: TABLE; Schema: forum; Owner: attrition_user
--

CREATE TABLE forum."ForumCategories" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Slug" text NOT NULL,
    "Description" text NOT NULL,
    "SortOrder" integer NOT NULL
);


ALTER TABLE forum."ForumCategories" OWNER TO attrition_user;

--
-- Name: ForumCategories_Id_seq; Type: SEQUENCE; Schema: forum; Owner: attrition_user
--

ALTER TABLE forum."ForumCategories" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME forum."ForumCategories_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ForumPosts; Type: TABLE; Schema: forum; Owner: attrition_user
--

CREATE TABLE forum."ForumPosts" (
    "Id" uuid NOT NULL,
    "ThreadId" uuid NOT NULL,
    "AuthorId" uuid NOT NULL,
    "AuthorName" text,
    "AuthorAvatar" text,
    "AuthorRole" text NOT NULL,
    "Content" text NOT NULL,
    "Attachments" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsRemoved" boolean NOT NULL,
    "RemovedReason" text,
    "RemovedByUserId" uuid,
    "RemovedByName" text,
    "RemovedAt" timestamp with time zone,
    "Depth" integer DEFAULT 0 NOT NULL,
    "ParentPostId" uuid
);


ALTER TABLE forum."ForumPosts" OWNER TO attrition_user;

--
-- Name: ForumReactions; Type: TABLE; Schema: forum; Owner: attrition_user
--

CREATE TABLE forum."ForumReactions" (
    "Id" uuid NOT NULL,
    "PostId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "ReactionType" text NOT NULL
);


ALTER TABLE forum."ForumReactions" OWNER TO attrition_user;

--
-- Name: ForumThreads; Type: TABLE; Schema: forum; Owner: attrition_user
--

CREATE TABLE forum."ForumThreads" (
    "Id" uuid NOT NULL,
    "CategoryId" integer NOT NULL,
    "Title" text NOT NULL,
    "AuthorId" uuid NOT NULL,
    "AuthorName" text,
    "AuthorAvatar" text,
    "IsPinned" boolean DEFAULT false NOT NULL,
    "IsLocked" boolean DEFAULT false NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "LastReplyAt" timestamp with time zone NOT NULL,
    "ReplyCount" integer NOT NULL,
    "WikiArticleId" uuid
);


ALTER TABLE forum."ForumThreads" OWNER TO attrition_user;

--
-- Name: PostReports; Type: TABLE; Schema: forum; Owner: attrition_user
--

CREATE TABLE forum."PostReports" (
    "Id" uuid NOT NULL,
    "PostId" uuid NOT NULL,
    "ReporterId" uuid NOT NULL,
    "ReporterName" text,
    "Reason" text NOT NULL,
    "Status" text DEFAULT 'Pending'::text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE forum."PostReports" OWNER TO attrition_user;

--
-- Name: ThreadSubscriptions; Type: TABLE; Schema: forum; Owner: attrition_user
--

CREATE TABLE forum."ThreadSubscriptions" (
    "Id" uuid NOT NULL,
    "ThreadId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "SubscribedAt" timestamp with time zone NOT NULL
);


ALTER TABLE forum."ThreadSubscriptions" OWNER TO attrition_user;

--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: forum; Owner: attrition_user
--

CREATE TABLE forum."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE forum."__EFMigrationsHistory" OWNER TO attrition_user;

--
-- Name: Notifications; Type: TABLE; Schema: identity; Owner: attrition_user
--

CREATE TABLE identity."Notifications" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Type" text NOT NULL,
    "Message" text NOT NULL,
    "Link" text,
    "ActorName" text,
    "IsRead" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE identity."Notifications" OWNER TO attrition_user;

--
-- Name: UserReports; Type: TABLE; Schema: identity; Owner: attrition_user
--

CREATE TABLE identity."UserReports" (
    "Id" uuid NOT NULL,
    "ReportedUserId" uuid NOT NULL,
    "ReportedUserName" text,
    "ReporterId" uuid NOT NULL,
    "ReporterName" text,
    "Reason" text NOT NULL,
    "Status" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE identity."UserReports" OWNER TO attrition_user;

--
-- Name: Users; Type: TABLE; Schema: identity; Owner: attrition_user
--

CREATE TABLE identity."Users" (
    "Id" uuid NOT NULL,
    "Username" text NOT NULL,
    "Email" text,
    "DisplayName" text,
    "PasswordHash" text,
    "GoogleId" text,
    "GoogleAvatarUrl" text,
    "AuthProvider" text NOT NULL,
    "Role" text DEFAULT 'User'::text NOT NULL,
    "AvatarPath" text,
    "BackgroundUrl" text,
    "Bio" text,
    "JoinedAt" timestamp with time zone DEFAULT now() NOT NULL,
    "ThemeMode" text NOT NULL,
    "ThemeAccent" text NOT NULL,
    "PostCount" integer NOT NULL,
    "ContributionCount" integer NOT NULL,
    "IsBanned" boolean DEFAULT false NOT NULL,
    "MustChangePassword" boolean DEFAULT false NOT NULL,
    "LastLoginAt" timestamp with time zone,
    "LastLoginIp" text,
    "FailedLoginAttempts" integer DEFAULT 0 NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "IsEmailVerified" boolean DEFAULT false NOT NULL,
    "EmailVerificationToken" text,
    "PendingEmail" text,
    "PasswordResetToken" text,
    "PasswordResetTokenExpiry" timestamp with time zone,
    "NotifyOnReply" boolean DEFAULT true NOT NULL,
    "NotifyOnMention" boolean DEFAULT true NOT NULL,
    "RefreshToken" text,
    "RefreshTokenExpiresAt" timestamp with time zone,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "EmailVerificationTokenExpiry" timestamp with time zone,
    "DeletedAt" timestamp with time zone,
    "IsDeleted" boolean DEFAULT false NOT NULL,
    "DeletionConfirmToken" text,
    "DeletionConfirmTokenExpiry" timestamp with time zone
);


ALTER TABLE identity."Users" OWNER TO attrition_user;

--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: identity; Owner: attrition_user
--

CREATE TABLE identity."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE identity."__EFMigrationsHistory" OWNER TO attrition_user;

--
-- Name: MusicAlbums; Type: TABLE; Schema: music; Owner: attrition_user
--

CREATE TABLE music."MusicAlbums" (
    "AlbumId" integer NOT NULL,
    "Title" text NOT NULL,
    "Slug" text NOT NULL,
    "Artists" text[] NOT NULL,
    "Description" text,
    "CoverPath" text,
    "IsCoverUserDefined" boolean NOT NULL,
    "Genre" text,
    "ReleaseDate" timestamp with time zone,
    "AlbumType" text NOT NULL,
    "TrackCount" integer NOT NULL,
    "TotalDuration" integer NOT NULL,
    "SortOrder" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE music."MusicAlbums" OWNER TO attrition_user;

--
-- Name: MusicAlbums_AlbumId_seq; Type: SEQUENCE; Schema: music; Owner: attrition_user
--

ALTER TABLE music."MusicAlbums" ALTER COLUMN "AlbumId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME music."MusicAlbums_AlbumId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: MusicPlaylists; Type: TABLE; Schema: music; Owner: attrition_user
--

CREATE TABLE music."MusicPlaylists" (
    "PlaylistId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Title" text NOT NULL,
    "Description" text,
    "IsPublic" boolean NOT NULL,
    "TrackCount" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE music."MusicPlaylists" OWNER TO attrition_user;

--
-- Name: MusicTracks; Type: TABLE; Schema: music; Owner: attrition_user
--

CREATE TABLE music."MusicTracks" (
    "TrackId" integer NOT NULL,
    "AlbumId" integer NOT NULL,
    "Title" text NOT NULL,
    "Slug" text NOT NULL,
    "Artists" text[] NOT NULL,
    "CoverPath" text,
    "TrackNumber" integer NOT NULL,
    "Duration" integer NOT NULL,
    "FilePath" text NOT NULL,
    "FileSize" bigint,
    "Genre" text,
    "Bpm" integer,
    "PlayCount" integer NOT NULL,
    "IsFeatured" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE music."MusicTracks" OWNER TO attrition_user;

--
-- Name: MusicTracks_TrackId_seq; Type: SEQUENCE; Schema: music; Owner: attrition_user
--

ALTER TABLE music."MusicTracks" ALTER COLUMN "TrackId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME music."MusicTracks_TrackId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: PlaylistTracks; Type: TABLE; Schema: music; Owner: attrition_user
--

CREATE TABLE music."PlaylistTracks" (
    "PlaylistId" uuid NOT NULL,
    "TrackId" integer NOT NULL,
    "Position" integer NOT NULL,
    "AddedAt" timestamp with time zone NOT NULL
);


ALTER TABLE music."PlaylistTracks" OWNER TO attrition_user;

--
-- Name: UserFavorites; Type: TABLE; Schema: music; Owner: attrition_user
--

CREATE TABLE music."UserFavorites" (
    "UserId" uuid NOT NULL,
    "TrackId" integer NOT NULL,
    "AddedAt" timestamp with time zone NOT NULL
);


ALTER TABLE music."UserFavorites" OWNER TO attrition_user;

--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: music; Owner: attrition_user
--

CREATE TABLE music."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE music."__EFMigrationsHistory" OWNER TO attrition_user;

--
-- Name: WikiArticles; Type: TABLE; Schema: wiki; Owner: attrition_user
--

CREATE TABLE wiki."WikiArticles" (
    "Id" uuid NOT NULL,
    "Title" text NOT NULL,
    "Slug" text NOT NULL,
    "CategoryId" integer NOT NULL,
    "Content" text NOT NULL,
    "CreatedById" uuid,
    "CreatedByName" text,
    "LastEditedById" uuid,
    "LastEditedByName" text,
    "Status" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE wiki."WikiArticles" OWNER TO attrition_user;

--
-- Name: WikiCategories; Type: TABLE; Schema: wiki; Owner: attrition_user
--

CREATE TABLE wiki."WikiCategories" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Slug" text NOT NULL,
    "Description" text NOT NULL,
    "IconUrl" text,
    "SortOrder" integer NOT NULL
);


ALTER TABLE wiki."WikiCategories" OWNER TO attrition_user;

--
-- Name: WikiCategories_Id_seq; Type: SEQUENCE; Schema: wiki; Owner: attrition_user
--

ALTER TABLE wiki."WikiCategories" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME wiki."WikiCategories_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: WikiContributions; Type: TABLE; Schema: wiki; Owner: attrition_user
--

CREATE TABLE wiki."WikiContributions" (
    "Id" uuid NOT NULL,
    "ArticleId" uuid NOT NULL,
    "ContributorId" uuid NOT NULL,
    "ContributorName" text,
    "SuggestedContent" text NOT NULL,
    "ChangeNote" text,
    "Status" text DEFAULT 'Pending'::text NOT NULL,
    "SubmittedAt" timestamp with time zone NOT NULL,
    "ReviewedAt" timestamp with time zone,
    "ReviewedById" uuid
);


ALTER TABLE wiki."WikiContributions" OWNER TO attrition_user;

--
-- Name: WikiRevisions; Type: TABLE; Schema: wiki; Owner: attrition_user
--

CREATE TABLE wiki."WikiRevisions" (
    "Id" uuid NOT NULL,
    "ArticleId" uuid NOT NULL,
    "Content" text NOT NULL,
    "EditedById" uuid,
    "EditedByName" text,
    "EditedAt" timestamp with time zone NOT NULL,
    "ChangeNote" text
);


ALTER TABLE wiki."WikiRevisions" OWNER TO attrition_user;

--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: wiki; Owner: attrition_user
--

CREATE TABLE wiki."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE wiki."__EFMigrationsHistory" OWNER TO attrition_user;

--
-- Name: Assets PK_Assets; Type: CONSTRAINT; Schema: assets; Owner: attrition_user
--

ALTER TABLE ONLY assets."Assets"
    ADD CONSTRAINT "PK_Assets" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: assets; Owner: attrition_user
--

ALTER TABLE ONLY assets."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: character; Owner: attrition_user
--

ALTER TABLE ONLY "character"."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: character_snapshots PK_character_snapshots; Type: CONSTRAINT; Schema: character; Owner: attrition_user
--

ALTER TABLE ONLY "character".character_snapshots
    ADD CONSTRAINT "PK_character_snapshots" PRIMARY KEY ("Id");


--
-- Name: characters PK_characters; Type: CONSTRAINT; Schema: character; Owner: attrition_user
--

ALTER TABLE ONLY "character".characters
    ADD CONSTRAINT "PK_characters" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: enemy; Owner: attrition_user
--

ALTER TABLE ONLY enemy."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: enemies PK_enemies; Type: CONSTRAINT; Schema: enemy; Owner: attrition_user
--

ALTER TABLE ONLY enemy.enemies
    ADD CONSTRAINT "PK_enemies" PRIMARY KEY ("EnemyId");


--
-- Name: enemy_loot PK_enemy_loot; Type: CONSTRAINT; Schema: enemy; Owner: attrition_user
--

ALTER TABLE ONLY enemy.enemy_loot
    ADD CONSTRAINT "PK_enemy_loot" PRIMARY KEY ("Id");


--
-- Name: ForumCategories PK_ForumCategories; Type: CONSTRAINT; Schema: forum; Owner: attrition_user
--

ALTER TABLE ONLY forum."ForumCategories"
    ADD CONSTRAINT "PK_ForumCategories" PRIMARY KEY ("Id");


--
-- Name: ForumPosts PK_ForumPosts; Type: CONSTRAINT; Schema: forum; Owner: attrition_user
--

ALTER TABLE ONLY forum."ForumPosts"
    ADD CONSTRAINT "PK_ForumPosts" PRIMARY KEY ("Id");


--
-- Name: ForumReactions PK_ForumReactions; Type: CONSTRAINT; Schema: forum; Owner: attrition_user
--

ALTER TABLE ONLY forum."ForumReactions"
    ADD CONSTRAINT "PK_ForumReactions" PRIMARY KEY ("Id");


--
-- Name: ForumThreads PK_ForumThreads; Type: CONSTRAINT; Schema: forum; Owner: attrition_user
--

ALTER TABLE ONLY forum."ForumThreads"
    ADD CONSTRAINT "PK_ForumThreads" PRIMARY KEY ("Id");


--
-- Name: PostReports PK_PostReports; Type: CONSTRAINT; Schema: forum; Owner: attrition_user
--

ALTER TABLE ONLY forum."PostReports"
    ADD CONSTRAINT "PK_PostReports" PRIMARY KEY ("Id");


--
-- Name: ThreadSubscriptions PK_ThreadSubscriptions; Type: CONSTRAINT; Schema: forum; Owner: attrition_user
--

ALTER TABLE ONLY forum."ThreadSubscriptions"
    ADD CONSTRAINT "PK_ThreadSubscriptions" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: forum; Owner: attrition_user
--

ALTER TABLE ONLY forum."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: Notifications PK_Notifications; Type: CONSTRAINT; Schema: identity; Owner: attrition_user
--

ALTER TABLE ONLY identity."Notifications"
    ADD CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id");


--
-- Name: UserReports PK_UserReports; Type: CONSTRAINT; Schema: identity; Owner: attrition_user
--

ALTER TABLE ONLY identity."UserReports"
    ADD CONSTRAINT "PK_UserReports" PRIMARY KEY ("Id");


--
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: identity; Owner: attrition_user
--

ALTER TABLE ONLY identity."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: identity; Owner: attrition_user
--

ALTER TABLE ONLY identity."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: MusicAlbums PK_MusicAlbums; Type: CONSTRAINT; Schema: music; Owner: attrition_user
--

ALTER TABLE ONLY music."MusicAlbums"
    ADD CONSTRAINT "PK_MusicAlbums" PRIMARY KEY ("AlbumId");


--
-- Name: MusicPlaylists PK_MusicPlaylists; Type: CONSTRAINT; Schema: music; Owner: attrition_user
--

ALTER TABLE ONLY music."MusicPlaylists"
    ADD CONSTRAINT "PK_MusicPlaylists" PRIMARY KEY ("PlaylistId");


--
-- Name: MusicTracks PK_MusicTracks; Type: CONSTRAINT; Schema: music; Owner: attrition_user
--

ALTER TABLE ONLY music."MusicTracks"
    ADD CONSTRAINT "PK_MusicTracks" PRIMARY KEY ("TrackId");


--
-- Name: PlaylistTracks PK_PlaylistTracks; Type: CONSTRAINT; Schema: music; Owner: attrition_user
--

ALTER TABLE ONLY music."PlaylistTracks"
    ADD CONSTRAINT "PK_PlaylistTracks" PRIMARY KEY ("PlaylistId", "TrackId");


--
-- Name: UserFavorites PK_UserFavorites; Type: CONSTRAINT; Schema: music; Owner: attrition_user
--

ALTER TABLE ONLY music."UserFavorites"
    ADD CONSTRAINT "PK_UserFavorites" PRIMARY KEY ("UserId", "TrackId");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: music; Owner: attrition_user
--

ALTER TABLE ONLY music."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: WikiArticles PK_WikiArticles; Type: CONSTRAINT; Schema: wiki; Owner: attrition_user
--

ALTER TABLE ONLY wiki."WikiArticles"
    ADD CONSTRAINT "PK_WikiArticles" PRIMARY KEY ("Id");


--
-- Name: WikiCategories PK_WikiCategories; Type: CONSTRAINT; Schema: wiki; Owner: attrition_user
--

ALTER TABLE ONLY wiki."WikiCategories"
    ADD CONSTRAINT "PK_WikiCategories" PRIMARY KEY ("Id");


--
-- Name: WikiContributions PK_WikiContributions; Type: CONSTRAINT; Schema: wiki; Owner: attrition_user
--

ALTER TABLE ONLY wiki."WikiContributions"
    ADD CONSTRAINT "PK_WikiContributions" PRIMARY KEY ("Id");


--
-- Name: WikiRevisions PK_WikiRevisions; Type: CONSTRAINT; Schema: wiki; Owner: attrition_user
--

ALTER TABLE ONLY wiki."WikiRevisions"
    ADD CONSTRAINT "PK_WikiRevisions" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: wiki; Owner: attrition_user
--

ALTER TABLE ONLY wiki."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: IX_Assets_AssetType; Type: INDEX; Schema: assets; Owner: attrition_user
--

CREATE INDEX "IX_Assets_AssetType" ON assets."Assets" USING btree ("AssetType");


--
-- Name: IX_character_snapshots_CharacterId_CapturedAt; Type: INDEX; Schema: character; Owner: attrition_user
--

CREATE INDEX "IX_character_snapshots_CharacterId_CapturedAt" ON "character".character_snapshots USING btree ("CharacterId", "CapturedAt");


--
-- Name: IX_characters_OwnerId; Type: INDEX; Schema: character; Owner: attrition_user
--

CREATE INDEX "IX_characters_OwnerId" ON "character".characters USING btree ("OwnerId");


--
-- Name: IX_characters_OwnerId_Name; Type: INDEX; Schema: character; Owner: attrition_user
--

CREATE UNIQUE INDEX "IX_characters_OwnerId_Name" ON "character".characters USING btree ("OwnerId", "Name");


--
-- Name: IX_enemies_Tier; Type: INDEX; Schema: enemy; Owner: attrition_user
--

CREATE INDEX "IX_enemies_Tier" ON enemy.enemies USING btree ("Tier");


--
-- Name: IX_enemy_loot_EnemyId; Type: INDEX; Schema: enemy; Owner: attrition_user
--

CREATE INDEX "IX_enemy_loot_EnemyId" ON enemy.enemy_loot USING btree ("EnemyId");


--
-- Name: IX_ForumCategories_Slug; Type: INDEX; Schema: forum; Owner: attrition_user
--

CREATE UNIQUE INDEX "IX_ForumCategories_Slug" ON forum."ForumCategories" USING btree ("Slug");


--
-- Name: IX_ForumPosts_ParentPostId; Type: INDEX; Schema: forum; Owner: attrition_user
--

CREATE INDEX "IX_ForumPosts_ParentPostId" ON forum."ForumPosts" USING btree ("ParentPostId");


--
-- Name: IX_ForumPosts_ThreadId; Type: INDEX; Schema: forum; Owner: attrition_user
--

CREATE INDEX "IX_ForumPosts_ThreadId" ON forum."ForumPosts" USING btree ("ThreadId");


--
-- Name: IX_ForumReactions_PostId_UserId; Type: INDEX; Schema: forum; Owner: attrition_user
--

CREATE UNIQUE INDEX "IX_ForumReactions_PostId_UserId" ON forum."ForumReactions" USING btree ("PostId", "UserId");


--
-- Name: IX_ForumThreads_CategoryId; Type: INDEX; Schema: forum; Owner: attrition_user
--

CREATE INDEX "IX_ForumThreads_CategoryId" ON forum."ForumThreads" USING btree ("CategoryId");


--
-- Name: IX_ForumThreads_WikiArticleId; Type: INDEX; Schema: forum; Owner: attrition_user
--

CREATE UNIQUE INDEX "IX_ForumThreads_WikiArticleId" ON forum."ForumThreads" USING btree ("WikiArticleId") WHERE ("WikiArticleId" IS NOT NULL);


--
-- Name: IX_PostReports_Status; Type: INDEX; Schema: forum; Owner: attrition_user
--

CREATE INDEX "IX_PostReports_Status" ON forum."PostReports" USING btree ("Status");


--
-- Name: IX_ThreadSubscriptions_ThreadId_UserId; Type: INDEX; Schema: forum; Owner: attrition_user
--

CREATE UNIQUE INDEX "IX_ThreadSubscriptions_ThreadId_UserId" ON forum."ThreadSubscriptions" USING btree ("ThreadId", "UserId");


--
-- Name: IX_Notifications_UserId_CreatedAt; Type: INDEX; Schema: identity; Owner: attrition_user
--

CREATE INDEX "IX_Notifications_UserId_CreatedAt" ON identity."Notifications" USING btree ("UserId", "CreatedAt");


--
-- Name: IX_Notifications_UserId_IsRead; Type: INDEX; Schema: identity; Owner: attrition_user
--

CREATE INDEX "IX_Notifications_UserId_IsRead" ON identity."Notifications" USING btree ("UserId", "IsRead");


--
-- Name: IX_UserReports_ReportedUserId; Type: INDEX; Schema: identity; Owner: attrition_user
--

CREATE INDEX "IX_UserReports_ReportedUserId" ON identity."UserReports" USING btree ("ReportedUserId");


--
-- Name: IX_UserReports_Status_CreatedAt; Type: INDEX; Schema: identity; Owner: attrition_user
--

CREATE INDEX "IX_UserReports_Status_CreatedAt" ON identity."UserReports" USING btree ("Status", "CreatedAt");


--
-- Name: IX_Users_Email; Type: INDEX; Schema: identity; Owner: attrition_user
--

CREATE UNIQUE INDEX "IX_Users_Email" ON identity."Users" USING btree ("Email");


--
-- Name: IX_Users_EmailVerificationToken; Type: INDEX; Schema: identity; Owner: attrition_user
--

CREATE INDEX "IX_Users_EmailVerificationToken" ON identity."Users" USING btree ("EmailVerificationToken") WHERE ("EmailVerificationToken" IS NOT NULL);


--
-- Name: IX_Users_GoogleId; Type: INDEX; Schema: identity; Owner: attrition_user
--

CREATE UNIQUE INDEX "IX_Users_GoogleId" ON identity."Users" USING btree ("GoogleId");


--
-- Name: IX_Users_PasswordResetToken; Type: INDEX; Schema: identity; Owner: attrition_user
--

CREATE INDEX "IX_Users_PasswordResetToken" ON identity."Users" USING btree ("PasswordResetToken") WHERE ("PasswordResetToken" IS NOT NULL);


--
-- Name: IX_Users_Username; Type: INDEX; Schema: identity; Owner: attrition_user
--

CREATE UNIQUE INDEX "IX_Users_Username" ON identity."Users" USING btree ("Username");


--
-- Name: IX_MusicAlbums_Slug; Type: INDEX; Schema: music; Owner: attrition_user
--

CREATE UNIQUE INDEX "IX_MusicAlbums_Slug" ON music."MusicAlbums" USING btree ("Slug");


--
-- Name: IX_MusicPlaylists_UserId; Type: INDEX; Schema: music; Owner: attrition_user
--

CREATE INDEX "IX_MusicPlaylists_UserId" ON music."MusicPlaylists" USING btree ("UserId");


--
-- Name: IX_MusicTracks_AlbumId_TrackNumber; Type: INDEX; Schema: music; Owner: attrition_user
--

CREATE UNIQUE INDEX "IX_MusicTracks_AlbumId_TrackNumber" ON music."MusicTracks" USING btree ("AlbumId", "TrackNumber");


--
-- Name: IX_WikiArticles_CategoryId; Type: INDEX; Schema: wiki; Owner: attrition_user
--

CREATE INDEX "IX_WikiArticles_CategoryId" ON wiki."WikiArticles" USING btree ("CategoryId");


--
-- Name: IX_WikiArticles_Slug; Type: INDEX; Schema: wiki; Owner: attrition_user
--

CREATE UNIQUE INDEX "IX_WikiArticles_Slug" ON wiki."WikiArticles" USING btree ("Slug");


--
-- Name: IX_WikiCategories_Slug; Type: INDEX; Schema: wiki; Owner: attrition_user
--

CREATE UNIQUE INDEX "IX_WikiCategories_Slug" ON wiki."WikiCategories" USING btree ("Slug");


--
-- Name: IX_WikiContributions_ArticleId; Type: INDEX; Schema: wiki; Owner: attrition_user
--

CREATE INDEX "IX_WikiContributions_ArticleId" ON wiki."WikiContributions" USING btree ("ArticleId");


--
-- Name: IX_WikiContributions_Status; Type: INDEX; Schema: wiki; Owner: attrition_user
--

CREATE INDEX "IX_WikiContributions_Status" ON wiki."WikiContributions" USING btree ("Status");


--
-- Name: IX_WikiRevisions_ArticleId; Type: INDEX; Schema: wiki; Owner: attrition_user
--

CREATE INDEX "IX_WikiRevisions_ArticleId" ON wiki."WikiRevisions" USING btree ("ArticleId");


--
-- Name: character_snapshots FK_character_snapshots_characters_CharacterId; Type: FK CONSTRAINT; Schema: character; Owner: attrition_user
--

ALTER TABLE ONLY "character".character_snapshots
    ADD CONSTRAINT "FK_character_snapshots_characters_CharacterId" FOREIGN KEY ("CharacterId") REFERENCES "character".characters("Id") ON DELETE CASCADE;


--
-- Name: enemy_loot FK_enemy_loot_enemies_EnemyId; Type: FK CONSTRAINT; Schema: enemy; Owner: attrition_user
--

ALTER TABLE ONLY enemy.enemy_loot
    ADD CONSTRAINT "FK_enemy_loot_enemies_EnemyId" FOREIGN KEY ("EnemyId") REFERENCES enemy.enemies("EnemyId") ON DELETE CASCADE;


--
-- Name: MusicTracks FK_MusicTracks_MusicAlbums_AlbumId; Type: FK CONSTRAINT; Schema: music; Owner: attrition_user
--

ALTER TABLE ONLY music."MusicTracks"
    ADD CONSTRAINT "FK_MusicTracks_MusicAlbums_AlbumId" FOREIGN KEY ("AlbumId") REFERENCES music."MusicAlbums"("AlbumId") ON DELETE CASCADE;


--
-- Name: PlaylistTracks FK_PlaylistTracks_MusicPlaylists_PlaylistId; Type: FK CONSTRAINT; Schema: music; Owner: attrition_user
--

ALTER TABLE ONLY music."PlaylistTracks"
    ADD CONSTRAINT "FK_PlaylistTracks_MusicPlaylists_PlaylistId" FOREIGN KEY ("PlaylistId") REFERENCES music."MusicPlaylists"("PlaylistId") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict aJBUlCgaBEkcGmEadpFiAAdZvaXRj6yBxNBvImVaTK3bUedrLgefQgb2Uj8w4vn

