// <auto-generated />
using System;
using Enemy.Service.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Enemy.Service.Migrations
{
    [DbContext(typeof(EnemyDbContext))]
    [Migration("20260721020510_AddUnitySyncAndSkills")]
    partial class AddUnitySyncAndSkills
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("enemy")
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Enemy.Service.Models.EnemyEntity", b =>
                {
                    b.Property<string>("EnemyId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Ad")
                        .HasColumnType("integer");

                    b.Property<int>("Ap")
                        .HasColumnType("integer");

                    b.Property<float>("AttackSpeed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(1f);

                    b.Property<float>("ChaseSpeed")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Def")
                        .HasColumnType("integer");

                    b.Property<int>("ExpReward")
                        .HasColumnType("integer");

                    b.Property<int>("GoldReward")
                        .HasColumnType("integer");

                    b.Property<int>("Hp")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRanged")
                        .HasColumnType("boolean");

                    b.Property<string>("Lore")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<float>("PatrolSpeed")
                        .HasColumnType("real");

                    b.Property<int>("Poise")
                        .HasColumnType("integer");

                    b.Property<float>("PoiseRecoveryTime")
                        .HasColumnType("real");

                    b.Property<int>("Res")
                        .HasColumnType("integer");

                    b.Property<string>("SpawnBiome")
                        .HasColumnType("text");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UnityBaselineJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EnemyId");

                    b.HasIndex("Tier");

                    b.ToTable("enemies", "enemy");
                });

            modelBuilder.Entity("Enemy.Service.Models.ItemEntity", b =>
                {
                    b.Property<string>("ItemId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("IconKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsKeyItem")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxStack")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UnityBaselineJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ItemId");

                    b.HasIndex("Category");

                    b.ToTable("items", "enemy");
                });

            modelBuilder.Entity("Enemy.Service.Models.SkillEntity", b =>
                {
                    b.Property<string>("SkillId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<float>("ActiveEndFrac")
                        .HasColumnType("real");

                    b.Property<float>("ActiveStartFrac")
                        .HasColumnType("real");

                    b.Property<float>("Angle")
                        .HasColumnType("real");

                    b.Property<float>("ApScaling")
                        .HasColumnType("real");

                    b.Property<int>("BaseDamage")
                        .HasColumnType("integer");

                    b.Property<float>("CastTime")
                        .HasColumnType("real");

                    b.Property<float>("Cooldown")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DamageType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Delivery")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Element")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("HitShape")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("KnockbackForce")
                        .HasColumnType("real");

                    b.Property<int>("ManaCost")
                        .HasColumnType("integer");

                    b.Property<float>("OffsetX")
                        .HasColumnType("real");

                    b.Property<float>("OffsetY")
                        .HasColumnType("real");

                    b.Property<int>("ProjectileCount")
                        .HasColumnType("integer");

                    b.Property<float>("ProjectileSpeed")
                        .HasColumnType("real");

                    b.Property<float>("Range")
                        .HasColumnType("real");

                    b.Property<float>("RectHeight")
                        .HasColumnType("real");

                    b.Property<float>("RectWidth")
                        .HasColumnType("real");

                    b.Property<float>("SpreadAngle")
                        .HasColumnType("real");

                    b.Property<float>("SweetSpotMultiplier")
                        .HasColumnType("real");

                    b.Property<float>("SweetSpotRadius")
                        .HasColumnType("real");

                    b.Property<float>("TickInterval")
                        .HasColumnType("real");

                    b.Property<string>("UnityBaselineJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("VfxLifetime")
                        .HasColumnType("real");

                    b.HasKey("SkillId");

                    b.ToTable("skills", "enemy");
                });

            modelBuilder.Entity("Enemy.Service.Models.EnemyEntity", b =>
                {
                    b.OwnsMany("Enemy.Service.Models.EnemyLootEntry", "LootTable", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<float>("DropChance")
                                .HasColumnType("real");

                            b1.Property<string>("EnemyId")
                                .IsRequired()
                                .HasColumnType("character varying(64)");

                            b1.Property<string>("IconKey")
                                .HasColumnType("text");

                            b1.Property<string>("ItemName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<short>("MaxQty")
                                .HasColumnType("smallint");

                            b1.Property<short>("MinQty")
                                .HasColumnType("smallint");

                            b1.Property<string>("Rarity")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.HasKey("Id");

                            b1.HasIndex("EnemyId");

                            b1.ToTable("enemy_loot", "enemy");

                            b1.WithOwner()
                                .HasForeignKey("EnemyId");
                        });

                    b.Navigation("LootTable");
                });

            modelBuilder.Entity("Enemy.Service.Models.ItemEntity", b =>
                {
                    b.OwnsMany("Enemy.Service.Models.ItemModifierEntry", "Modifiers", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("Amount")
                                .HasColumnType("integer");

                            b1.Property<string>("ItemId")
                                .IsRequired()
                                .HasColumnType("character varying(64)");

                            b1.Property<string>("Stat")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.HasKey("Id");

                            b1.HasIndex("ItemId");

                            b1.ToTable("item_modifiers", "enemy");

                            b1.WithOwner()
                                .HasForeignKey("ItemId");
                        });

                    b.Navigation("Modifiers");
                });
#pragma warning restore 612, 618
        }
    }
}
