// <auto-generated />
using System;
using Enemy.Service.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Enemy.Service.Migrations
{
    [DbContext(typeof(EnemyDbContext))]
    partial class EnemyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("enemy")
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Enemy.Service.Models.EnemyEntity", b =>
                {
                    b.Property<string>("EnemyId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Ad")
                        .HasColumnType("integer");

                    b.Property<int>("Ap")
                        .HasColumnType("integer");

                    b.Property<float>("AttackSpeed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(1f);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Def")
                        .HasColumnType("integer");

                    b.Property<int>("ExpReward")
                        .HasColumnType("integer");

                    b.Property<int>("GoldReward")
                        .HasColumnType("integer");

                    b.Property<int>("Hp")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRanged")
                        .HasColumnType("boolean");

                    b.Property<string>("Lore")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Res")
                        .HasColumnType("integer");

                    b.Property<string>("SpawnBiome")
                        .HasColumnType("text");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EnemyId");

                    b.HasIndex("Tier");

                    b.ToTable("enemies", "enemy");
                });

            modelBuilder.Entity("Enemy.Service.Models.EnemyEntity", b =>
                {
                    b.OwnsMany("Enemy.Service.Models.EnemyLootEntry", "LootTable", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<float>("DropChance")
                                .HasColumnType("real");

                            b1.Property<string>("EnemyId")
                                .IsRequired()
                                .HasColumnType("character varying(64)");

                            b1.Property<string>("IconKey")
                                .HasColumnType("text");

                            b1.Property<string>("ItemName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<short>("MaxQty")
                                .HasColumnType("smallint");

                            b1.Property<short>("MinQty")
                                .HasColumnType("smallint");

                            b1.Property<string>("Rarity")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.HasKey("Id");

                            b1.HasIndex("EnemyId");

                            b1.ToTable("enemy_loot", "enemy");

                            b1.WithOwner()
                                .HasForeignKey("EnemyId");
                        });

                    b.Navigation("LootTable");
                });
#pragma warning restore 612, 618
        }
    }
}
